import { Link, useRouterState } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { ArrowUpRight, ArrowDown, Menu, X, Plus, Minus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { projects, services } from '@/lib/wrute';

const nav = [{ to: '/work', label: 'Work' }, { to: '/services', label: 'Services' }, { to: '/studio', label: 'Studio' }] as const;
export function SiteHeader() {
 const [open, setOpen] = useState(false);
 const path = useRouterState({ select: state => state.location.pathname });
 useEffect(() => setOpen(false), [path]);
 return <header className="site-header"><Link to="/" aria-label="Wrute home" className="wordmark">wrute<span className="text-primary">.</span></Link><nav aria-label="Main navigation" className="hidden items-center gap-9 md:flex">{nav.map(item => <Button key={item.to} asChild variant="ghost" className="nav-link"><Link to={item.to} activeProps={{ className: 'nav-link active' }}>{item.label}</Link></Button>)}</nav><div className="flex items-center gap-3"><Button asChild variant="editorialOutline" className="contact-link"><Link to="/contact">Let’s talk <ArrowUpRight /></Link></Button><Button variant="ghost" size="icon" className="md:hidden" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</Button></div>{open && <nav aria-label="Mobile navigation" className="mobile-nav">{nav.map(item => <Button asChild variant="ghost" key={item.to}><Link to={item.to}>{item.label}<ArrowUpRight /></Link></Button>)}</nav>}</header>;
}
export function SiteFooter() { return <footer className="site-footer"><div className="page-width"><div className="footer-top"><div><p className="eyebrow">Your next chapter starts here</p><h2>Let’s make<br />something <span className="text-primary">matter.</span></h2></div><Button asChild variant="editorial" className="footer-cta"><Link to="/contact" aria-label="Start a project"><ArrowUpRight /></Link></Button></div><div className="footer-bottom"><Link to="/" className="wordmark">wrute<span className="text-primary">.</span></Link><p>Independent minds. Distinctive design.</p><div className="flex gap-5"><Link to="/work">Work</Link><Link to="/services">Services</Link><Link to="/contact">Contact</Link></div><span>© 2026 Wrute</span></div></div></footer>; }
export function ProjectGrid({ limit, filter = 'All' }: { limit?: number; filter?: string }) { const list = projects.filter(p => filter === 'All' || p.filter === filter).slice(0, limit); return <div className="project-grid">{list.map((project, index) => <Link key={project.slug} to="/work/$slug" params={{ slug: project.slug }} className="project group"><div className="project-image"><img src={project.image} alt={`${project.name} concept brand identity and packaging`} width={1408} height={1104} loading="lazy" /><span className="project-view"><ArrowUpRight /></span><span className="project-concept">Concept project</span></div><div className="project-caption"><div><h3>{project.name}</h3><p>{project.category}</p></div><span className="project-number">0{index + 1}<ArrowUpRight /></span></div></Link>)}</div>; }
export function ServiceList() { const [open, setOpen] = useState<number | null>(0); return <div className="service-list">{services.map((service, index) => <div key={service.name} className="service-row"><Button variant="ghost" className="service-toggle" aria-expanded={open === index} onClick={() => setOpen(open === index ? null : index)}><span className="service-index">0{index + 1}</span><span className="service-title">{service.name}</span><span className="service-note">{service.note}</span>{open === index ? <Minus /> : <Plus />}</Button>{open === index && <div className="service-detail"><p>{service.description}</p><span>{service.items}</span></div>}</div>)}</div>; }
export function PageIntro({ label, title, copy }: { label: string; title: string; copy: string }) { return <div className="page-intro"><p className="eyebrow">{label}</p><h1>{title}</h1><p className="intro-copy">{copy}</p></div>; }
export function DownLink() { return <Button variant="ghost" size="icon" aria-label="Explore selected work" className="hero-down" onClick={() => document.getElementById('selected-work')?.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' })}><ArrowDown /></Button>; }
