import { useEffect, useRef, useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import type { UIMessage } from "ai";
import {
  ArrowLeft,
  ArrowUp,
  Check,
  Copy,
  Download,
  MessageSquare,
  PanelLeft,
  Paperclip,
  PenLine,
  Search,
  Trash2,
  X,
} from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { Button } from "@/components/ui/button";
import {
  Conversation,
  ConversationContent,
  ConversationScrollButton,
} from "@/components/ai-elements/conversation";
import {
  Message,
  MessageContent,
  MessageResponse,
  MessageActions,
  MessageAction,
} from "@/components/ai-elements/message";
import {
  PromptInput,
  PromptInputTextarea,
  PromptInputFooter,
  PromptInputSubmit,
} from "@/components/ai-elements/prompt-input";
import { createThread, loadThreads, saveThreads, type ChatThread } from "@/lib/chat-store";
import {
  PLATFORMS_DATA,
  findPlatform,
  findAgent,
  type AgentCategoryItem,
  type PlatformItem,
} from "@/lib/agents-data";
import { AgentPlatformSelector } from "@/components/agent-platform-selector";

interface SpeechRecognitionEventLike {
  resultIndex: number;
  results: {
    length: number;
    [index: number]: {
      [index: number]: {
        transcript: string;
      };
    };
  };
}

interface SpeechRecognitionInstance {
  continuous: boolean;
  interimResults: boolean;
  lang: string;
  start: () => void;
  stop: () => void;
  onstart: (() => void) | null;
  onresult: ((event: SpeechRecognitionEventLike) => void) | null;
  onerror: (() => void) | null;
  onend: (() => void) | null;
}

function Brand({ small = false }: { small?: boolean }) {
  return (
    <span className={`font-display font-semibold ${small ? "text-xl" : "text-3xl"}`}>
      wellio<span className="text-ink-soft">.</span>
    </span>
  );
}

function generateAnswer(query: string, agentCategory?: string, _platformId?: string): string {
  const q = query.trim().toLowerCase();

  // Greeting & basic queries
  if (/^(hi|hello|hey|sup|good morning|good afternoon|good evening)\b/i.test(q)) {
    if (agentCategory) {
      return `Hello! I'm your **${agentCategory}** intelligence assistant. How can I help you analyze data, review trends, or generate insights today?`;
    }
    return "Hello! I'm Wellio. How can I help you explore your ideas or work on your project today?";
  }

  // GoodDoc HMS domain responses
  if (agentCategory === "Patient Insights" || /patient|demographics|visit frequency/i.test(q)) {
    return `### Patient Insights Summary\n\n• **New vs Returning**: 42% new patient registrations (318 patients), 58% returning visits (439 patients) over the last 30 days.\n• **Demographics**: Primary age bracket is 28–45 years (46%), followed by 46–60 years (31%). Geographic distribution: 68% local metro, 32% referral regions.\n• **Visit Frequency**: Average recurrence interval is 4.2 weeks for chronic care clinics; general OP average is 2.1 visits annually.\n\n*Would you like a department-level demographic breakdown or patient retention cohort analysis?*`;
  }
  if (agentCategory === "Appointment Management" || /appointment|no-show|cancellation/i.test(q)) {
    return `### Appointment Management Overview\n\n• **Total Bookings**: 1,280 appointments scheduled this week.\n• **Completion Rate**: 88.4% completed successfully.\n• **No-Show Rate**: 4.6% (down 1.2% following automated SMS/WhatsApp reminders).\n• **Cancellation Trends**: 7.0% cancellations, primarily concentrated in weekday evening slots.\n• **Follow-Up Compliance**: 83% of recommended follow-ups booked within the advised 14-day window.\n\n*Recommended action: Enable automatic standby slot reallocation for cancellations.*`;
  }
  if (agentCategory === "Doctor Insights" || /doctor|consultation count|workload/i.test(q)) {
    return `### Doctor Insights & Workload Analytics\n\n• **Consultation Volume**: 842 consultations completed across 24 specialists this week.\n• **Average Consultation Time**: 16.4 minutes per patient.\n• **Workload Distribution**: Cardiology and Orthopedics operating at 94% slot capacity; Pediatrics at 78%.\n• **Revenue Contribution**: Highest OP revenue generated by General Surgery and Interventional Cardiology.\n\n*Review schedule balancing to relieve peak morning slots for senior consultants.*`;
  }
  if (
    agentCategory === "Department Insights" ||
    /department|radiology|lab performance|op vs ip/i.test(q)
  ) {
    return `### Department Performance Review\n\n• **OP vs IP Performance**: OP clinic volume up 8% WoW; IP admissions stable at 84% bed utilization.\n• **Radiology**: 312 MRI/CT scans conducted; average report turnaround time is 2.4 hours.\n• **Clinical Lab**: 2,840 diagnostic panels processed with 99.1% on-time report delivery.\n• **Pharmacy Throughput**: Average prescription dispensing duration is 4.8 minutes.\n\n*Identified bottleneck: Evening ultrasound scheduling backlog.*`;
  }
  if (agentCategory === "Financial Insights" || /financial|revenue|billing|insurance/i.test(q)) {
    return `### Financial & Billing Intelligence\n\n• **Gross Collections**: $142,600 collected today ($98,400 digital/UPI/card, $44,200 cash).\n• **Insurance Claims**: $48,200 pending insurer adjudication; average reimbursement turnaround is 11 days.\n• **Outstanding Balances**: Accounts receivable aging >30 days reduced by 14% this month.\n• **Discharge Clearance**: Average billing clearance time per IP discharge is 38 minutes.`;
  }
  if (agentCategory === "Pharmacy Intelligence" || /pharmacy|medicine|low stock|expiry/i.test(q)) {
    return `### Pharmacy Intelligence & Inventory\n\n• **Daily Medicine Sales**: $28,950 across 1,140 prescriptions dispensed.\n• **Low Stock Alert**: 6 critical medications below buffer reorder point (including Amoxicillin 500mg, Atorvastatin 20mg).\n• **Expiry Watch**: 4 batches expiring within 30 days flagged for priority rotation or vendor return.\n• **Inventory Turnover**: Top 20 fast-moving drugs maintaining 18-day turnover velocity.`;
  }
  if (agentCategory === "Laboratory Intelligence" || /laboratory|test volume|delay/i.test(q)) {
    return `### Laboratory Operations & Diagnostics\n\n• **Test Volume**: 1,480 samples processed in last 24 hours.\n• **TAT Performance**: 95.8% tests reported within standard turnaround time window.\n• **Delays Flagged**: Histopathology cultures running an average 3.2-hour delay due to specialized staining.\n• **Revenue**: Diagnostics revenue up 6.4% MoM driven by preventive health checkup packages.`;
  }
  if (
    agentCategory === "Bed & Admission Analytics" ||
    /bed|occupancy|admission|discharge/i.test(q)
  ) {
    return `### Bed & Admission Analytics\n\n• **Occupancy Rate**: Overall 83.5% (ICU: 91.2%, Semi-Private: 85.0%, General Ward: 78.4%).\n• **Current Census**: 214 occupied beds, 42 available beds for emergency intake.\n• **Admissions & Discharges**: 28 admissions today vs 31 planned discharges.\n• **Average Length of Stay (ALOS)**: 3.7 days across all clinical specialties.`;
  }
  if (
    agentCategory === "Queue & Waiting Analysis" ||
    /queue|waiting time|bottleneck|token/i.test(q)
  ) {
    return `### Queue & Waiting Time Analysis\n\n• **Average Waiting Time**: 14.8 minutes from token generation to triage assessment.\n• **Consultation Queue**: 18.2 minutes average wait for doctor consultation.\n• **Peak Bottlenecks**: 09:30 AM – 11:15 AM in OP Clinic Blocks B & C.\n• **Token Velocity**: 118 tokens processed per hour across 8 active consultation suites.`;
  }
  if (
    agentCategory === "Operational Efficiency" ||
    /operational|registration|productivity/i.test(q)
  ) {
    return `### Operational Efficiency Scorecard\n\n• **Front Office Productivity**: Average patient registration duration is 2.6 minutes per patient.\n• **Billing Counters**: 4.1 minutes per complex insurance settlement.\n• **Staff Utilization**: Front desk staffing running at optimal 86% capacity index.\n• **Process Improvements**: Digital pre-registration reduced lobby crowding by 22%.`;
  }
  if (agentCategory === "Patient Journey" || /patient journey|timeline/i.test(q)) {
    return `### End-to-End Patient Journey Timeline\n\n• **Step 1: Check-in / Registration**: 03m 10s\n• **Step 2: Vitals & Triage**: 06m 45s\n• **Step 3: Waiting Lounge**: 14m 20s\n• **Step 4: Doctor Consultation**: 17m 30s\n• **Step 5: Lab / Diagnostics**: 11m 15s\n• **Step 6: Pharmacy & Settlement**: 07m 40s\n• **Total Journey Duration**: ~60 minutes end-to-end for standard OP visits.`;
  }
  if (agentCategory === "Compliance & Audit" || /compliance|audit|records/i.test(q)) {
    return `### Compliance & Medical Audit Report\n\n• **Documentation Compliance**: 97.4% completion rate for mandatory clinical notes.\n• **Pending Sign-Offs**: 8 discharge summaries awaiting senior physician sign-off.\n• **Audit Logs**: Zero unauthorized access attempts detected in past 30 days.\n• **Accreditation Readiness**: NABH/JCI protocol adherence score at 96.8%.`;
  }
  if (agentCategory === "AI Recommendations" || /recommendation|staffing|workflow/i.test(q)) {
    return `### AI Workflow & Staffing Recommendations\n\n1. **Dynamic Nurse Allocation**: Reassign 2 staff nurses from Ward D to Emergency Care during the 18:00–22:00 surge.\n2. **Staggered Slot Booking**: Open 15-minute staggered buffers for Cardiology clinics to reduce peak queue build-up.\n3. **Pharmacy Auto-Reorder**: Trigger expedited purchase orders for 4 fast-moving antibiotics based on predicted flu season spike.`;
  }
  if (agentCategory === "Executive Briefing" || /executive|briefing|summary/i.test(q)) {
    return `### Executive Daily Business Briefing\n\n• **Financial**: Gross revenue: $184,200 (+7.4% vs target).\n• **Clinical**: 912 total patients served (710 OP, 202 IP); bed occupancy at 84%.\n• **Operational**: Zero critical clinical safety incidents reported.\n• **Satisfaction**: Overall patient net promoter score (NPS) at 91.4.\n• **Outlook**: 38 planned surgical procedures scheduled for tomorrow across 6 operating theaters.`;
  }

  // GoodDoc Kiosk domain responses
  if (agentCategory === "Check-in Analytics" || /check-in|checkin time/i.test(q)) {
    return `### Kiosk Check-in Analytics\n\n• **Total Check-Ins**: 1,420 patients checked in via self-service kiosks today.\n• **Average Check-In Duration**: 44 seconds per patient.\n• **Adoption Share**: 68% of all arriving OP patients used kiosks instead of physical front desk.\n• **Error Rate**: 1.2% invalid phone or unlinked MRN attempts successfully redirected.`;
  }
  if (agentCategory === "Queue Insights" || /kiosk.*queue|busiest hours/i.test(q)) {
    return `### Kiosk Queue Insights\n\n• **Peak Traffic Hours**: 08:30 AM – 10:15 AM and 02:00 PM – 03:30 PM.\n• **Terminal Queue Length**: Average 1.3 patients waiting in line per kiosk terminal.\n• **Token Dispatch**: 100% of tokens synced in real-time to central overhead LED display boards.`;
  }
  if (agentCategory === "Feature Usage" || /feature usage|reports|booking/i.test(q)) {
    return `### Kiosk Feature Usage Breakdown\n\n• **Check-In & Token Generation**: 56% of total sessions.\n• **Bill Payment (UPI/Card)**: 19% of total sessions.\n• **Diagnostic Report Printing**: 14% of sessions (840 printed report pages).\n• **Appointment Booking & Rescheduling**: 7% of sessions.\n• **Hospital Wayfinding & Maps**: 4% of sessions.`;
  }
  if (agentCategory === "Device Health" || /device health|printer status|scanner/i.test(q)) {
    return `### Device Health & Hardware Diagnostics\n\n• **Active Terminals**: 18 of 18 kiosks currently online and responsive.\n• **Printer Paper Status**: 16 terminals OK, 2 terminals (Lobby B, Floor 2) at <15% paper roll capacity.\n• **Barcode & QR Scanners**: 100% operational with 0.1% read failure rate.\n• **Hardware Temperature**: All internal thermal units within safe operating thresholds (<42°C).`;
  }
  if (agentCategory === "User Experience" || /user experience|drop-off|failed session/i.test(q)) {
    return `### Kiosk User Experience & Drop-Offs\n\n• **Session Completion Rate**: 96.8% completed without operator assistance.\n• **Drop-Off Points**: 1.8% abandon during specialty selection; 1.4% during OTP validation.\n• **Retry Rate**: 2.1% of patients re-scanned QR code for authentication.\n• **Average User Rating**: 4.8 / 5 based on 320 on-screen satisfaction prompts.`;
  }
  if (agentCategory === "Language Insights" || /language|tamil|malayalam|english/i.test(q)) {
    return `### Multilingual Usage Analytics\n\n• **Tamil**: 52% of all completed kiosk sessions.\n• **English**: 32% of sessions (predominantly among younger demographics and corporate staff).\n• **Malayalam**: 16% of sessions (high concentration in outpatient surgical care units).\n• **Insight**: Tamil language interface showed the lowest drop-off rate (1.1%).`;
  }
  if (agentCategory === "Payment Analytics" || /kiosk.*payment|collections/i.test(q)) {
    return `### Kiosk Payment Analytics\n\n• **Total Collections**: $24,800 processed through kiosk POS terminals today.\n• **Payment Methods**: UPI QR Code (64%), Contactless NFC/Cards (31%), Net Banking (5%).\n• **Average Transaction**: $28.50 per consultation token / diagnostic copay.\n• **Transaction Failure Rate**: 0.6% due to bank gateway timeout; all automatically refunded.`;
  }
  if (agentCategory === "Location Performance" || /location performance|hospital/i.test(q)) {
    return `### Kiosk Performance by Hospital Branch\n\n• **Main Hospital (Lobby Central)**: 840 check-ins/day (82% kiosk adoption).\n• **City Care Outpatient Center**: 410 check-ins/day (74% kiosk adoption).\n• **North Metro Clinic**: 170 check-ins/day (61% adoption; signage enhancement recommended).`;
  }
  if (agentCategory === "Usage Trends" || /usage trends|adoption/i.test(q)) {
    return `### Adoption Trends (Past 90 Days)\n\n• **Month 1**: 48% self-service share.\n• **Month 2**: 59% self-service share.\n• **Month 3 (Current)**: 68% self-service share (+20% quarterly growth).\n• **Impact**: Front desk registration desk queues reduced by 52 minutes daily.`;
  }
  if (agentCategory === "Service Optimization" || /kiosk.*optimization/i.test(q)) {
    return `### AI Recommendations for Kiosk Optimization\n\n1. **Quick-Rebook Button**: Add a 1-tap "Repeat Last Doctor" prompt on greeting screen to save 12s per repeat patient.\n2. **Voice Prompts**: Enable optional audio cues in Tamil and Malayalam for elderly patients.\n3. **Lobby Flow**: Relocate Kiosk #3 and #4 closer to entrance walkway to balance load.`;
  }
  if (agentCategory === "Maintenance Alerts" || /maintenance|alerts/i.test(q)) {
    return `### Kiosk Maintenance & Hardware Alerts\n\n• **Unit #04 (Floor 2)**: Thermal printer head scheduled for cleaning (3,800 receipts printed).\n• **Unit #09 (Pediatrics)**: Touchscreen calibration recommended.\n• **Zero Critical Faults**: All systems responding with <120ms network latency.`;
  }

  // A Style domain responses
  if (agentCategory === "Sales Insights" || /sales|revenue|orders|gmv/i.test(q)) {
    return `### Sales Insights & Performance\n\n• **Gross Merchandise Value (GMV)**: $86,400 this week (+14.2% YoY).\n• **Order Volume**: 1,280 orders fulfilled with an Average Order Value (AOV) of $67.50.\n• **Sales Channel Split**: Brand Website (48%), Retail Flagship (36%), Mobile App (16%).\n• **Conversion Rate**: 3.8% across digital storefronts.`;
  }
  if (agentCategory === "Product Performance" || /best sellers|poor performers/i.test(q)) {
    return `### Product Performance Breakdown\n\n• **Top Sellers**: Relaxed Linen Button-Down (412 units sold), High-Rise Wide Leg Pant (340 units), Silk Blend Wrap Dress (280 units).\n• **Slow Moving**: Quilted Utility Vest (14 units sold in 45 days), Corduroy Overshirt (22 units).\n• **Gross Margin**: Linen apparel line delivering highest gross margin at 68.2%.`;
  }
  if (agentCategory === "Inventory Intelligence" || /inventory|dead stock|stockout/i.test(q)) {
    return `### Inventory Intelligence\n\n• **Stockout Alerts**: Sizes M & L in Olive and Natural tones below safety stock in central warehouse.\n• **Dead Stock**: 8 SKUs with zero units moved in 60+ days ($6,400 tied-up inventory value).\n• **Turnover Ratio**: 4.8x annual inventory velocity across apparel lines.`;
  }
  if (agentCategory === "Return Intelligence" || /return/i.test(q)) {
    return `### Return Intelligence & Reasons\n\n• **Overall Return Rate**: 13.8% (well below industry fashion average of 22%).\n• **Reason Breakdown**: Sizing / Fit (56%), Color Variance (22%), Changed Mind (16%), Defect (6%).\n• **Actionable Insight**: Adding detailed fit guides on dress product pages projected to reduce returns by 18%.`;
  }
  if (agentCategory === "Customer Insights" || /customer|repeat|loyal/i.test(q)) {
    return `### Customer Demographics & Loyalty\n\n• **Customer Mix**: 46% repeat customers, 54% first-time buyers.\n• **VIP Loyalty Tier**: Top 12% of customers account for 38% of total quarterly revenue.\n• **Customer Lifetime Value (LTV)**: $320 average 12-month value.\n• **Acquisition Cost (CAC)**: $24.50 with a 13.1x LTV:CAC ratio.`;
  }
  if (agentCategory === "Order Management" || /order management|shipped|pending/i.test(q)) {
    return `### Order Fulfillment & Dispatch\n\n• **Orders In Pipeline**: 142 orders pending packing, 318 shipped in transit.\n• **Dispatch SLA**: 96.4% of orders dispatched within 24 hours of placement.\n• **Delivery Turnaround**: 2.8 business days average transit time.\n• **Cancellation Rate**: 1.2% pre-shipment cancellations.`;
  }
  if (agentCategory === "Store Performance" || /store performance|channels/i.test(q)) {
    return `### Channel Comparison: Online vs Retail\n\n• **Online Storefront**: $48,200 revenue, 58% gross margin, 42,000 monthly visits.\n• **Flagship Retail Stores**: $38,200 revenue, 64% gross margin, 34% higher units-per-transaction.\n• **Omnichannel**: 18% of customers shop both online and in-store, spending 2.4x more annually.`;
  }
  if (agentCategory === "Category Analysis" || /men's|women's|kids/i.test(q)) {
    return `### Category Performance Analytics\n\n• **Women's Apparel**: 58% revenue share (+18% YoY growth).\n• **Men's Apparel**: 32% revenue share (+9% YoY growth).\n• **Kids & Youth**: 10% revenue share (highest repeat repurchase velocity).`;
  }
  if (agentCategory === "Demand Forecasting" || /forecast|predict/i.test(q)) {
    return `### Predictive Demand Forecast\n\n• **Upcoming Festive Collection**: Projected 35% surge in ethnic fusion wear and festive embroidery.\n• **Fabric Lead Times**: Recommend placing raw linen and viscose yarn orders 45 days in advance.\n• **Safety Stock**: Increase buffer for Sizes M & L by 25% ahead of holiday promotions.`;
  }
  if (agentCategory === "Trend Analysis" || /trend|colours|styles/i.test(q)) {
    return `### Apparel Trend Analysis\n\n• **Color Palettes**: Sage Green, Terracotta, Butter Yellow, and Warm Ecru driving 62% of fashion purchases.\n• **Silhouettes**: Relaxed tailoring, breathable natural textiles, and boxy short-sleeve fits leading search demand.\n• **Fabric Preference**: 100% Cotton and Washed Linen dominating customer reviews.`;
  }
  if (agentCategory === "Merchandising" || /merchandising|assortment/i.test(q)) {
    return `### Merchandising Recommendations\n\n1. **Hero Display**: Position Linen Essentials and Silk Wrap silhouettes on primary homepage carousel and store entrance.\n2. **Bundle Pricing**: Launch "Complete Look" bundles (Shirt + Trousers) with 10% discount to elevate AOV above $80.\n3. **Markdown Strategy**: Apply gradual 15% markdown on winter vests to clear aging inventory before season cutoff.`;
  }

  // Generic fallback response
  if (/brand|perspective|idea|design|project|strategy/i.test(q)) {
    return `Here are a few clear insights on "${query.trim()}":\n\n1. **Core Clarity**: Strip back unnecessary complexity and focus on the primary message you want to communicate.\n2. **Target Audience**: Frame your perspective around the exact need or curiosity of your audience.\n3. **Actionable Direction**: Prototype the simplest version first to test and iterate rapidly.\n\nWhat specific angle would you like to dive into next?`;
  }
  return `Here is a perspective on "${query.trim()}":\n\n• **Core Concept**: Focus on the most impactful element and refine it for clarity.\n• **Execution**: Break down the process into small, manageable milestones.\n• **Refinement**: Eliminate friction and let the strongest ideas stand out.\n\nLet me know how you'd like to take this forward!`;
}

export function ChatScreen({ threadId }: { threadId?: string }) {
  const navigate = useNavigate();
  const [threads, setThreads] = useState<ChatThread[]>([]);
  const [ready, setReady] = useState(false);
  const [sidebar, setSidebar] = useState(false);
  const [searching, setSearching] = useState(false);
  const [search, setSearch] = useState("");
  const [draft, setDraft] = useState("");
  const [copied, setCopied] = useState<string | null>(null);
  const [storageError, setStorageError] = useState(false);
  const [isThinking, setIsThinking] = useState(false);
  const thinkingTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const textarea = useRef<HTMLTextAreaElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [attachments, setAttachments] = useState<File[]>([]);
  const [isListening, setIsListening] = useState(false);
  const recognitionRef = useRef<SpeechRecognitionInstance | null>(null);
  const audioContextRef = useRef<AudioContext | null>(null);
  const micStreamRef = useRef<MediaStream | null>(null);
  const animFrameRef = useRef<number | null>(null);
  const [waveBars, setWaveBars] = useState<number[]>(() => new Array(68).fill(3));

  // Platform selection state
  const [activePlatformId, setActivePlatformId] = useState<string>("gooddoc-hms");

  useEffect(() => {
    return () => {
      if (thinkingTimer.current) clearTimeout(thinkingTimer.current);
      if (recognitionRef.current) {
        try {
          recognitionRef.current.stop();
        } catch {
          // ignore error on stop
        }
      }
      if (micStreamRef.current) {
        micStreamRef.current.getTracks().forEach((track) => track.stop());
      }
      if (audioContextRef.current && audioContextRef.current.state !== "closed") {
        try {
          audioContextRef.current.close();
        } catch {
          // ignore error on close
        }
      }
      if (animFrameRef.current) {
        cancelAnimationFrame(animFrameRef.current);
      }
    };
  }, []);

  useEffect(() => {
    if (!isListening) {
      if (micStreamRef.current) {
        micStreamRef.current.getTracks().forEach((track) => track.stop());
        micStreamRef.current = null;
      }
      if (audioContextRef.current && audioContextRef.current.state !== "closed") {
        try {
          audioContextRef.current.close();
        } catch {
          // ignore error on close
        }
        audioContextRef.current = null;
      }
      if (animFrameRef.current) {
        cancelAnimationFrame(animFrameRef.current);
        animFrameRef.current = null;
      }
      setWaveBars(new Array(68).fill(3));
      return;
    }

    let isCancelled = false;
    let fallbackInterval: ReturnType<typeof setInterval> | null = null;

    if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
      navigator.mediaDevices
        .getUserMedia({ audio: true })
        .then((stream) => {
          if (isCancelled) {
            stream.getTracks().forEach((t) => t.stop());
            return;
          }
          micStreamRef.current = stream;
          const AudioCtx =
            window.AudioContext ||
            (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
          if (!AudioCtx) return;

          const ctx = new AudioCtx();
          audioContextRef.current = ctx;
          const analyser = ctx.createAnalyser();
          analyser.fftSize = 64;
          analyser.smoothingTimeConstant = 0.5;

          const source = ctx.createMediaStreamSource(stream);
          source.connect(analyser);

          const dataArray = new Uint8Array(analyser.frequencyBinCount);

          const updateWave = () => {
            if (isCancelled) return;
            analyser.getByteFrequencyData(dataArray);

            let sum = 0;
            for (let i = 0; i < dataArray.length; i++) {
              sum += dataArray[i] ?? 0;
            }
            const avg = sum / dataArray.length;
            const norm = Math.min(1, avg / 35);

            const nextBars = new Array(68).fill(3);
            if (norm > 0.05) {
              const time = Date.now() / 120;
              for (let i = 0; i < 68; i++) {
                const wave1 = Math.sin((i / 68) * Math.PI * 3 + time);
                const wave2 = Math.cos((i / 68) * Math.PI * 4 - time * 0.7);
                const packet = Math.max(0, wave1 * wave2);
                const barHeight = 3 + packet * norm * 26;
                nextBars[i] = Math.max(3, Math.min(26, Math.round(barHeight)));
              }
            }
            setWaveBars(nextBars);
            animFrameRef.current = requestAnimationFrame(updateWave);
          };

          updateWave();
        })
        .catch(() => {
          runSimulation();
        });
    } else {
      runSimulation();
    }

    function runSimulation() {
      let step = 0;
      fallbackInterval = setInterval(() => {
        if (isCancelled) return;
        step += 1;
        const isSpeaking = step % 9 < 6;
        const nextBars = new Array(68).fill(3);
        if (isSpeaking) {
          const center1 = (Math.sin(step * 0.35) * 0.3 + 0.38) * 68;
          const center2 = (Math.cos(step * 0.28) * 0.2 + 0.72) * 68;
          for (let i = 0; i < 68; i++) {
            const d1 = Math.abs(i - center1);
            const d2 = Math.abs(i - center2);
            const g1 = Math.exp(-(d1 * d1) / 16) * 24;
            const g2 = Math.exp(-(d2 * d2) / 14) * 20;
            const val = 3 + Math.max(g1, g2) * (0.65 + Math.random() * 0.35);
            nextBars[i] = Math.max(3, Math.min(26, Math.round(val)));
          }
        }
        setWaveBars(nextBars);
      }, 85);
    }

    return () => {
      isCancelled = true;
      if (fallbackInterval) clearInterval(fallbackInterval);
      if (micStreamRef.current) {
        micStreamRef.current.getTracks().forEach((track) => track.stop());
        micStreamRef.current = null;
      }
      if (audioContextRef.current && audioContextRef.current.state !== "closed") {
        try {
          audioContextRef.current.close();
        } catch {
          // ignore error on close
        }
        audioContextRef.current = null;
      }
      if (animFrameRef.current) {
        cancelAnimationFrame(animFrameRef.current);
        animFrameRef.current = null;
      }
    };
  }, [isListening]);

  function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    if (e.target.files) {
      const files = Array.from(e.target.files);
      setAttachments((prev) => [...prev, ...files]);
    }
  }

  function removeAttachment(index: number) {
    setAttachments((prev) => prev.filter((_, i) => i !== index));
  }

  function toggleListening() {
    if (isListening) {
      if (recognitionRef.current) {
        try {
          recognitionRef.current.stop();
        } catch {
          // ignore error on stop
        }
      }
      setIsListening(false);
      return;
    }

    setIsListening(true);

    const win = window as unknown as {
      SpeechRecognition?: new () => SpeechRecognitionInstance;
      webkitSpeechRecognition?: new () => SpeechRecognitionInstance;
    };
    const SpeechRecognition = win.SpeechRecognition || win.webkitSpeechRecognition;

    if (SpeechRecognition) {
      try {
        const recognition = new SpeechRecognition();
        recognition.continuous = true;
        recognition.interimResults = true;
        recognition.lang = "en-US";

        recognition.onstart = () => {
          setIsListening(true);
        };

        recognition.onresult = (event: SpeechRecognitionEventLike) => {
          let transcript = "";
          for (let i = event.resultIndex; i < event.results.length; i++) {
            transcript += event.results[i]?.[0]?.transcript ?? "";
          }
          if (transcript.trim()) {
            setDraft((prev) => (prev ? `${prev} ${transcript.trim()}` : transcript.trim()));
          }
        };

        recognition.onerror = () => {
          setIsListening(false);
        };

        recognition.onend = () => {
          setIsListening(false);
        };

        recognitionRef.current = recognition;
        recognition.start();
      } catch {
        setIsListening(false);
      }
    } else {
      setIsListening(true);
      setTimeout(() => {
        setDraft((prev) => (prev ? prev : "Voice note: check hospital admission trends"));
        setIsListening(false);
      }, 4000);
    }
  }

  useEffect(() => {
    let stored = loadThreads();
    if (threadId && !stored.some((t) => t.id === threadId)) {
      stored = [{ ...createThread(), id: threadId }, ...stored];
      try {
        saveThreads(stored);
      } catch {
        setStorageError(true);
      }
    }
    setThreads(stored);
    setReady(true);
  }, [threadId]);

  const active = threads.find((t) => t.id === threadId);
  const messages = active?.messages || [];

  // Active agent and platform metadata if attached to current thread
  const activePlatform = findPlatform(active?.platformId || activePlatformId);
  const currentAgentMeta = findAgent(
    active?.platformId || activePlatform?.id,
    active?.agentCategory,
  );

  // Focus textarea when in chat mode
  useEffect(() => {
    if (active?.agentCategory || messages.length > 0) {
      textarea.current?.focus();
    }
  }, [ready, threadId, messages.length, active?.agentCategory]);

  function update(next: ChatThread[]) {
    try {
      saveThreads(next);
      setStorageError(false);
    } catch {
      setStorageError(true);
    }
    setThreads(next);
  }

  // When clicking "New conversation", reset to platform/agents directory
  function newChat() {
    setSidebar(false);
    setDraft("");
    setAttachments([]);
    if (isListening && recognitionRef.current) {
      try {
        recognitionRef.current.stop();
      } catch {
        // ignore error on stop
      }
      setIsListening(false);
    }
    void navigate({ to: "/" });
  }

  // When user clicks ANY agent in the agents list
  function handleSelectAgent(
    platform: PlatformItem,
    agent: AgentCategoryItem,
    initialQuestion?: string,
  ) {
    const thread = createThread(platform.id, agent.category);
    thread.title = `${agent.category} (${platform.shortName})`;

    let initialMessages: UIMessage[] = [];
    if (initialQuestion) {
      const userMsg: UIMessage = {
        id: crypto.randomUUID(),
        role: "user",
        parts: [{ type: "text", text: initialQuestion }],
      };
      initialMessages = [userMsg];
      thread.messages = initialMessages;
    }

    const nextThreads = [thread, ...threads.filter((t) => t.id !== thread.id)];
    update(nextThreads);

    void navigate({ to: "/chat/$threadId", params: { threadId: thread.id } });

    if (initialQuestion) {
      setIsThinking(true);
      if (thinkingTimer.current) clearTimeout(thinkingTimer.current);

      thinkingTimer.current = setTimeout(() => {
        const assistantMsg: UIMessage = {
          id: crypto.randomUUID(),
          role: "assistant",
          parts: [
            {
              type: "text",
              text: generateAnswer(initialQuestion, agent.category, platform.name),
            },
          ],
        };
        const threadWithAssistant = {
          ...thread,
          updatedAt: Date.now(),
          messages: [...initialMessages, assistantMsg],
        };
        update([threadWithAssistant, ...threads.filter((t) => t.id !== thread.id)]);
        setIsThinking(false);
      }, 1000);
    }
  }

  function handleBackToAgents() {
    void navigate({ to: "/" });
  }

  function send(text: string) {
    const trimmed = text.trim();
    if (!trimmed && attachments.length === 0) return;
    if (isListening && recognitionRef.current) {
      try {
        recognitionRef.current.stop();
      } catch {
        // ignore error on stop
      }
      setIsListening(false);
    }
    const attachmentNote = attachments.length
      ? `\n\n[Attached: ${attachments.map((f) => f.name).join(", ")}]`
      : "";
    const fullText = (trimmed || "Uploaded attachment(s)") + attachmentNote;
    const current = active || createThread(activePlatform?.id, active?.agentCategory);
    const user: UIMessage = {
      id: crypto.randomUUID(),
      role: "user",
      parts: [{ type: "text", text: fullText }],
    };
    const threadWithUser = {
      ...current,
      title: current.messages.length
        ? current.title
        : current.agentCategory
          ? `${current.agentCategory}`
          : (trimmed || "Attachment").slice(0, 48),
      updatedAt: Date.now(),
      messages: [...current.messages, user],
    };
    update([threadWithUser, ...threads.filter((t) => t.id !== current.id)]);
    setDraft("");
    setAttachments([]);
    if (!active) void navigate({ to: "/chat/$threadId", params: { threadId: current.id } });

    setIsThinking(true);
    if (thinkingTimer.current) clearTimeout(thinkingTimer.current);

    thinkingTimer.current = setTimeout(() => {
      const assistant: UIMessage = {
        id: crypto.randomUUID(),
        role: "assistant",
        parts: [
          {
            type: "text",
            text: generateAnswer(trimmed, current.agentCategory, current.platformId),
          },
        ],
      };
      const threadWithAssistant = {
        ...threadWithUser,
        updatedAt: Date.now(),
        messages: [...threadWithUser.messages, assistant],
      };
      update([threadWithAssistant, ...threads.filter((t) => t.id !== current.id)]);
      setIsThinking(false);
    }, 1100);

    requestAnimationFrame(() => textarea.current?.focus());
  }

  function remove(id: string) {
    update(threads.filter((t) => t.id !== id));
    if (id === threadId) void navigate({ to: "/" });
  }

  function download() {
    if (!active) return;
    const text = active.messages
      .map(
        (m) =>
          `${m.role}: ${m.parts
            .filter((p) => p.type === "text")
            .map((p) => p.text)
            .join("\n")}`,
      )
      .join("\n\n");
    const url = URL.createObjectURL(new Blob([text], { type: "text/plain" }));
    const a = document.createElement("a");
    a.href = url;
    a.download = `${active.title.replace(/[^a-z0-9]/gi, "-").slice(0, 48)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const canSend = Boolean(draft.trim() || attachments.length > 0);

  // Determine whether to show the Agent Platform Selector or Chat UI
  const isChatView = Boolean(
    threadId && active && (active.agentCategory || active.messages.length > 0),
  );

  const renderComposer = () => (
    <div className="w-full">
      <motion.div
        initial={false}
        animate={{
          height: isListening ? 50 : 120,
          borderRadius: isListening ? 25 : 12,
        }}
        transition={{ duration: 0.35, ease: [0.16, 1, 0.3, 1] }}
        className="chat-card relative w-full overflow-hidden border border-border bg-card shadow-xs"
        style={{ willChange: "height, border-radius" }}
      >
        {/* Voice recording listening bar view */}
        <motion.div
          key="voice-bar-view"
          initial={false}
          animate={{
            opacity: isListening ? 1 : 0,
            scale: isListening ? 1 : 0.98,
            pointerEvents: isListening ? "auto" : "none",
          }}
          transition={{ duration: 0.22, ease: "easeInOut" }}
          className="absolute inset-0 flex h-full w-full items-center justify-between px-3.5"
          aria-hidden={!isListening}
        >
          <div className="flex h-full flex-1 items-center justify-center overflow-hidden pr-2">
            <div className="flex w-full items-center justify-between gap-[3px]">
              {waveBars.map((height, idx) => (
                <span
                  key={idx}
                  className={`w-[2.5px] rounded-full transition-all duration-75 ${
                    height > 4 ? "bg-foreground" : "bg-ink-soft/30"
                  }`}
                  style={{ height: `${height}px` }}
                />
              ))}
            </div>
          </div>
          <button
            type="button"
            onClick={toggleListening}
            aria-label="Stop recording"
            className="flex size-7 cursor-pointer items-center justify-center rounded-full bg-foreground text-background transition-transform active:scale-90"
          >
            <span className="size-2 rounded-xs bg-background" />
          </button>
        </motion.div>

        {/* Standard Text/Input Composer view */}
        <motion.div
          key="text-composer-view"
          initial={false}
          animate={{
            opacity: isListening ? 0 : 1,
            pointerEvents: isListening ? "none" : "auto",
          }}
          transition={{ duration: 0.2 }}
          className="chat-composer flex h-full flex-col justify-between"
        >
          <PromptInput
            onSubmit={() => send(draft)}
            className="flex h-full flex-col justify-between border-0 bg-transparent p-0 shadow-none"
          >
            <PromptInputTextarea
              ref={textarea}
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              placeholder={
                active?.agentCategory
                  ? `Ask ${active.agentCategory} intelligence…`
                  : "Ask anything or describe your task…"
              }
              aria-label="Message prompt"
              className="min-h-[48px] flex-1 resize-none border-0 bg-transparent px-3.5 pt-3 text-sm text-foreground placeholder:text-ink-soft focus-visible:ring-0"
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  send(draft);
                }
              }}
            />

            {/* Display attached files if any */}
            {attachments.length > 0 && (
              <div className="flex flex-wrap gap-1.5 px-3.5 pb-1">
                {attachments.map((file, idx) => (
                  <div
                    key={idx}
                    className="inline-flex items-center gap-1.5 rounded border border-border bg-surface-soft px-2 py-0.5 text-xs text-foreground"
                  >
                    <span className="max-w-[140px] truncate">{file.name}</span>
                    <button
                      type="button"
                      onClick={() => removeAttachment(idx)}
                      className="cursor-pointer text-ink-soft hover:text-foreground"
                      aria-label={`Remove ${file.name}`}
                    >
                      <X className="size-3" />
                    </button>
                  </div>
                ))}
              </div>
            )}

            <PromptInputFooter className="mt-auto flex items-center justify-between border-0 bg-transparent px-3 pb-2 pt-0">
              {/* Left side: Attach option */}
              <div className="flex items-center">
                <button
                  type="button"
                  onClick={() => fileInputRef.current?.click()}
                  className="inline-flex size-9 cursor-pointer items-center justify-center rounded-md text-ink-soft transition-colors hover:bg-surface-soft hover:text-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                  title="Attach file"
                  aria-label="Attach file"
                >
                  <Paperclip className="size-4.5" />
                </button>
                <input
                  ref={fileInputRef}
                  type="file"
                  multiple
                  className="hidden"
                  onChange={handleFileChange}
                />
              </div>

              {/* Right side: Wave button when empty, Sent button when typing */}
              <div className="flex items-center">
                <AnimatePresence mode="wait">
                  {canSend ? (
                    <motion.div
                      key="send-option-btn"
                      initial={{ scale: 0.85, opacity: 0 }}
                      animate={{ scale: 1, opacity: 1 }}
                      exit={{ scale: 0.85, opacity: 0 }}
                      transition={{ duration: 0.15 }}
                    >
                      <PromptInputSubmit
                        status={isThinking ? "submitted" : "ready"}
                        disabled={!canSend || !ready}
                        aria-label="Send message"
                        className="size-10 shrink-0 rounded-md shadow-none"
                      >
                        <ArrowUp className="size-5" />
                      </PromptInputSubmit>
                    </motion.div>
                  ) : (
                    <motion.button
                      key="wave-btn"
                      type="button"
                      initial={{ scale: 0.85, opacity: 0 }}
                      animate={{ scale: 1, opacity: 1 }}
                      exit={{ scale: 0.85, opacity: 0 }}
                      transition={{ duration: 0.15 }}
                      onClick={toggleListening}
                      title="Voice input"
                      aria-label="Voice input"
                      className="inline-flex size-9 cursor-pointer items-center justify-center rounded-md text-ink-soft transition-colors hover:bg-surface-soft hover:text-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                    >
                      <div
                        className="flex h-5 items-center justify-center gap-[2.5px]"
                        aria-hidden="true"
                      >
                        <span className="h-[6px] w-[2.5px] rounded-full bg-ink-soft" />
                        <span className="h-[12px] w-[2.5px] rounded-full bg-ink-soft" />
                        <span className="h-[18px] w-[2.5px] rounded-full bg-ink-soft" />
                        <span className="h-[12px] w-[2.5px] rounded-full bg-ink-soft" />
                        <span className="h-[6px] w-[2.5px] rounded-full bg-ink-soft" />
                      </div>
                    </motion.button>
                  )}
                </AnimatePresence>
              </div>
            </PromptInputFooter>
          </PromptInput>
        </motion.div>
      </motion.div>
      {storageError && (
        <p role="alert" className="mt-3 px-1 text-xs text-alert">
          Unable to save. Check your browser storage.
        </p>
      )}
    </div>
  );

  return (
    <main className="chat-shell flex h-dvh min-h-0 bg-canvas text-foreground">
      {sidebar && (
        <div
          className="fixed inset-0 z-30 bg-foreground/30 md:hidden"
          onClick={() => setSidebar(false)}
        />
      )}
      <aside
        className={`chat-sidebar fixed inset-y-0 left-0 z-40 flex w-72 shrink-0 flex-col border-r border-border bg-surface-soft p-5 md:static md:w-64 lg:w-72 ${sidebar ? "flex" : "hidden md:flex"}`}
      >
        <div className="mb-8 flex items-center justify-between px-2">
          <Link to="/" aria-label="Wellio home" onClick={newChat}>
            <Brand />
          </Link>
          <Button
            variant="ghost"
            size="icon"
            title="Close sidebar"
            aria-label="Close sidebar"
            className="md:hidden"
            onClick={() => setSidebar(false)}
          >
            <X />
          </Button>
        </div>
        <Button
          variant="editorial"
          onClick={newChat}
          className="h-12 justify-between rounded-md px-4"
        >
          New conversation
          <PenLine />
        </Button>
        <Button
          variant="ghost"
          onClick={() => setSearching(!searching)}
          className="mt-2 h-11 justify-start px-4 text-ink-soft"
        >
          <Search />
          Search chats
        </Button>
        {searching && (
          <input
            autoFocus
            aria-label="Search conversations"
            placeholder="Search…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="mt-2 h-10 w-full rounded-md border border-border bg-card px-3 text-sm outline-none focus:border-foreground"
          />
        )}
        <div className="mt-8 px-3 text-xs font-medium text-ink-soft">
          <span>Recent chats</span>
        </div>
        <nav aria-label="Conversations" className="mt-3 flex-1 space-y-1 overflow-y-auto">
          {threads
            .filter((t) => t.title.toLowerCase().includes(search.toLowerCase()))
            .map((t) => (
              <div
                key={t.id}
                className={`group flex items-center rounded-md ${t.id === threadId ? "bg-card" : "hover:bg-card/60"}`}
              >
                <Button
                  asChild
                  variant="ghost"
                  className="h-11 min-w-0 flex-1 justify-start px-3 hover:bg-transparent"
                >
                  <Link
                    to="/chat/$threadId"
                    params={{ threadId: t.id }}
                    onClick={() => {
                      setSidebar(false);
                      setDraft("");
                    }}
                  >
                    <MessageSquare className="size-4 shrink-0 text-ink-soft" />
                    <span className="truncate text-xs">{t.title}</span>
                  </Link>
                </Button>
                <Button
                  size="icon-sm"
                  variant="ghost"
                  aria-label={`Delete ${t.title}`}
                  title="Delete conversation"
                  className="mr-1 shrink-0 text-ink-soft md:opacity-0 md:group-hover:opacity-100 md:focus-visible:opacity-100"
                  onClick={() => remove(t.id)}
                >
                  <Trash2 className="size-3.5" />
                </Button>
              </div>
            ))}
          {ready && !threads.length && (
            <p className="px-3 py-4 text-xs text-ink-soft">No conversations yet</p>
          )}
        </nav>
      </aside>

      <section className="relative flex min-w-0 flex-1 flex-col bg-white">
        <header className="flex h-16 shrink-0 items-center justify-between gap-3 px-5 sm:px-9">
          <div className="flex min-w-0 items-center gap-3">
            <Button
              variant="ghost"
              size="icon"
              aria-label="Open sidebar"
              title="Open sidebar"
              className="md:hidden"
              onClick={() => setSidebar(true)}
            >
              <PanelLeft />
            </Button>
            <span className="md:hidden">
              <Brand small />
            </span>

            {isChatView ? (
              <div className="flex min-w-0 items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleBackToAgents}
                  className="h-8 gap-1.5 rounded-md px-2.5 text-xs text-ink-soft hover:text-foreground"
                >
                  <ArrowLeft className="size-3.5" />
                  <span>All Agents</span>
                </Button>
                <span className="hidden text-xs text-ink-soft/40 sm:inline">/</span>
                <span className="hidden truncate text-xs text-ink-soft sm:inline">
                  {activePlatform?.name}
                </span>
                <span className="hidden text-xs text-ink-soft/40 sm:inline">/</span>
                <span className="truncate text-sm font-semibold text-foreground">
                  {active?.agentCategory || active?.title || "Conversation"}
                </span>
              </div>
            ) : (
              <span className="hidden truncate text-sm font-medium text-foreground md:block">
                Agents Directory
              </span>
            )}
          </div>
          <div className="flex items-center gap-2">
            {messages.length > 0 && (
              <Button
                size="icon"
                variant="ghost"
                title="Download conversation"
                aria-label="Download conversation"
                onClick={download}
              >
                <Download />
              </Button>
            )}
          </div>
        </header>

        {/* View Mode Switching: Agent Platform Selector vs Chat UI */}
        {!isChatView ? (
          <AgentPlatformSelector
            activePlatformId={activePlatformId}
            onSelectPlatform={setActivePlatformId}
            onSelectAgent={handleSelectAgent}
          />
        ) : messages.length === 0 ? (
          /* Chat UI: New agent conversation empty state - Clean, Beautiful, Uncluttered */
          <div className="flex min-h-0 flex-1 flex-col items-center justify-center overflow-y-auto px-6 py-8 sm:px-9">
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3, ease: "easeOut" }}
              className="w-full max-w-3xl -translate-y-4 sm:-translate-y-6"
            >
              <div className="mb-6">
                <div className="mb-2 flex items-center gap-2">
                  <span className="inline-flex items-center rounded border border-border bg-surface-soft px-2 py-0.5 text-xs font-medium text-ink-soft">
                    {activePlatform?.name || "Intelligence Agent"}
                  </span>
                </div>
                <h1 className="font-display text-4xl font-semibold tracking-tight text-foreground sm:text-5xl">
                  {active?.agentCategory || "What's on your mind?"}
                </h1>
                {currentAgentMeta && (
                  <p className="mt-2 text-base text-ink-soft sm:text-lg leading-relaxed">
                    {currentAgentMeta.whatUsersCanAsk}
                  </p>
                )}
              </div>

              {renderComposer()}
            </motion.div>
          </div>
        ) : (
          /* Chat UI: Active Conversation with messages */
          <>
            <Conversation className="min-h-0" key={threadId}>
              <ConversationContent className="mx-auto w-full max-w-3xl gap-8 px-5 py-10 sm:px-8">
                {messages.map((m) => (
                  <Message key={m.id} from={m.role} className="max-w-full">
                    {m.role === "assistant" && (
                      <span className="font-display text-sm font-bold">
                        {active?.agentCategory ? `${active.agentCategory} • ` : ""}wellio.
                      </span>
                    )}
                    <MessageContent className="text-base leading-7 group-[.is-user]:bg-primary group-[.is-user]:text-primary-foreground group-[.is-user]:rounded-md">
                      {m.parts.map((p, i) =>
                        p.type === "text" ? (
                          <MessageResponse key={i}>{p.text}</MessageResponse>
                        ) : null,
                      )}
                    </MessageContent>
                    <MessageActions className="justify-end">
                      <MessageAction
                        tooltip="Copy message"
                        onClick={async () => {
                          try {
                            await navigator.clipboard.writeText(
                              m.parts
                                .filter((p) => p.type === "text")
                                .map((p) => p.text)
                                .join("\n"),
                            );
                            setCopied(m.id);
                            setTimeout(() => setCopied(null), 1500);
                          } catch {
                            setCopied(null);
                          }
                        }}
                      >
                        {copied === m.id ? <Check /> : <Copy />}
                      </MessageAction>
                    </MessageActions>
                  </Message>
                ))}
                {isThinking && (
                  <div className="flex flex-col gap-2 max-w-full">
                    <span className="font-display text-sm font-bold">
                      {active?.agentCategory ? `${active.agentCategory} • ` : ""}wellio.
                    </span>
                    <div
                      className="flex items-center gap-1.5 py-2 px-1"
                      role="status"
                      aria-label="Loading response"
                    >
                      <motion.span
                        className="size-2 rounded-full bg-foreground/60"
                        animate={{ y: [0, -6, 0] }}
                        transition={{ duration: 0.6, repeat: Infinity, ease: "easeInOut" }}
                      />
                      <motion.span
                        className="size-2 rounded-full bg-foreground/60"
                        animate={{ y: [0, -6, 0] }}
                        transition={{
                          duration: 0.6,
                          repeat: Infinity,
                          delay: 0.15,
                          ease: "easeInOut",
                        }}
                      />
                      <motion.span
                        className="size-2 rounded-full bg-foreground/60"
                        animate={{ y: [0, -6, 0] }}
                        transition={{
                          duration: 0.6,
                          repeat: Infinity,
                          delay: 0.3,
                          ease: "easeInOut",
                        }}
                      />
                    </div>
                  </div>
                )}
              </ConversationContent>
              <ConversationScrollButton aria-label="Scroll to latest message" />
            </Conversation>
            <motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.25, ease: "easeOut" }}
              className="shrink-0 px-5 pb-5 pt-3 sm:px-9 sm:pb-7"
            >
              <div className="mx-auto max-w-3xl">{renderComposer()}</div>
            </motion.div>
          </>
        )}
      </section>
    </main>
  );
}
